Correção
ericbreno/Ward-matriculas-ufcg pull request #2
Opened 2018-08-18 18:34 UTC by dnrocha1

2018-08-18 18:49 UTC, kaiokassiano commented
Hi Daniyel,

Please refer at this commit [1], where we did increase time between sending verifications in order to avoid causing overload on the server.

Lower intervals previously caused a crash on the "Controle Acadêmico". We don't want this to happen again.

[1]: https://github.com/ericbreno/Ward-matriculas-ufcg/commit/376646f2797ede6f71e6878278343f25b5dfdc07

2018-08-18 18:53 UTC, kaiokmo requested changes
Hi Daniyel,

Please refer at this commit [1], where we did increase time between sending verifications, in order to avoid causing overload on the server.

Lower intervals previously caused a crash on the "Controle Acadêmico". We don't want this to happen again.

[1]: https://github.com/ericbreno/Ward-matriculas-ufcg/commit/376646f2797ede6f71e6878278343f25b5dfdc07

2018-08-18 18:53 UTC, kaiokassiano commented on bot/pre.py
> +            time.sleep(2)
Please, keep this fixed at 15.

2018-09-13 11:28 UTC, ericbreno approved these changes

2018-09-13 11:28 UTC, merged